### ISSUE TITLE
Widget not working

### ISSUE THREAD

**Issue by mirandaio** [ebi-gene-expression-group/scxa-tsne-widget#3]
Hi, here is a minimal web app that uses the `TSnePlotWidget` component https://scxa-widget.netlify.com
Unfortunately, it is not working. It looks like the component is making some Ajax requests internally that are failing because they are being done to the wrong url.

Here is the part of the code that attempts to use the React component:

https://github.com/mirandaio/scxa-widget/blob/master/src/App.js#L7

This web app has been bootstrapped using [create-react-app](https://facebook.github.io/create-react-app/) (which is what the Open Targets platform app used).

**Comment by alfonsomunozpomer** [comment]
Hi @mirandaio,

By default the component was pointing at an Expression Atlas instance running on `localhost`. I’ve published a new version `1.0.0-rc2` tha fixes the issue by using our public service.

**Comment by mirandaio** [comment]
Hi @alfonsomunozpomer,

It's working now. Thanks for the quick fix.
